-- migration_015_fix_shared_channels.sql
-- Fix: shared channels (e.g. WhatsApp) need to map the same external_id
-- to MULTIPLE properties. The old UNIQUE(channel, external_id) prevented this
-- because upserting property B would overwrite property A's mapping.
--
-- Solution: change the unique constraint to (channel, external_id, property_id)
-- so each property can have its own mapping for the same channel+external_id.

-- ═══════════════════════════════════════════════════════
-- 1. Drop old unique constraint and index
-- ═══════════════════════════════════════════════════════

-- Drop the old unique constraint (name auto-generated by Postgres)
ALTER TABLE channel_property_map
  DROP CONSTRAINT IF EXISTS channel_property_map_channel_external_id_key;

-- Drop the old partial index (was optimized for the old unique pair)
DROP INDEX IF EXISTS idx_channel_property_map_lookup;

-- ═══════════════════════════════════════════════════════
-- 2. Add new unique constraint: (channel, external_id, property_id)
-- ═══════════════════════════════════════════════════════

ALTER TABLE channel_property_map
  ADD CONSTRAINT channel_property_map_channel_external_id_property_id_key
  UNIQUE (channel, external_id, property_id);

-- ═══════════════════════════════════════════════════════
-- 3. Recreate partial index for fast webhook lookup
-- ═══════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_channel_property_map_lookup
  ON channel_property_map(channel, external_id) WHERE is_active = true;

-- ═══════════════════════════════════════════════════════
-- 4. Re-seed shared WhatsApp mapping for Tayrona (was impossible before)
-- ═══════════════════════════════════════════════════════

DO $$
DECLARE
  tayrona_id UUID;
BEGIN
  SELECT id INTO tayrona_id FROM properties WHERE slug = 'tayrona' LIMIT 1;

  IF tayrona_id IS NOT NULL THEN
    INSERT INTO channel_property_map (property_id, channel, external_id, external_name, scope)
    VALUES (tayrona_id, 'whatsapp', '101206379439613', '+573234392420 (compartido)', 'shared')
    ON CONFLICT (channel, external_id, property_id) DO UPDATE SET
      external_name = EXCLUDED.external_name,
      scope = EXCLUDED.scope,
      updated_at = now();
  END IF;
END $$;
